# Generated by Django 2.2.2 on 2019-06-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='machine',
            field=models.TextField(default=''),
        ),
    ]
