# Generated by Django 2.1.8 on 2019-06-21 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cet', '0002_job_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distributor',
            name='hours',
        ),
        migrations.AddField(
            model_name='distributor',
            name='close_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='distributor',
            name='open_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
