# Generated by Django 2.1.8 on 2019-06-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cet', '0004_auto_20190624_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturer',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
